# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
import numpy as np

EJERCICIO 1: Crear un arreglo de ceros de longitud 12

In [2]:
arreglo1 = np.zeros(12)
print(arreglo1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


EJERCICIO 2: Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

In [3]:
arreglo2 = np.zeros(10)
arreglo2[4]= 10
print(arreglo2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


EJERCICIO 3: Crear un arreglo que tenga los números del 10 al 49

In [4]:
arreglo3 = np.arange(10,50)
print(arreglo3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


EJERCICIO 4: Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [5]:
arreglo4 = np.arange(9).reshape((3,3))
print(arreglo4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


EJERCICIO 5: Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [12]:
arreglo5 = np.random.rand(100)
print(np.mean(arreglo5))
print(np.var(arreglo5))
#print(arreglo5)

0.444804396274482
0.08564450814039137


EJERCICIO 6: Calcular la media de un arreglo usando np.sum

In [13]:
media_calc = np.sum(arreglo5)/len(arreglo5)
print(media_calc)

0.444804396274482


EJERCICIO 7: Calcular la varianza de un arreglo usando np.sum y np.mean

In [14]:
media = np.mean(arreglo5)
arreglo_int= (arreglo5-media)**2
var_calc = (np.sum(arreglo_int)/(len(arreglo5)))

print(var_calc)

0.08564450814039137


EJERCICIO 8: Crear un array de números aleatorios usando np.random.randn.

In [9]:
arreglo8 = np.random.randn(20)
print(arreglo8)

[ 0.08716249  2.29101625 -0.80347082 -0.36016302 -0.94060847  0.58215014
  1.73658415 -0.19963813  1.49941809  0.21973854  1.58398977 -0.77828269
  0.85902464 -2.29043497 -0.39572025  0.01081648  0.10664814 -0.46005364
 -0.54165543 -1.91169326]
